apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: CI-CD_1ST-deployment
spec:
  selector:
    matchLabels:
      app: CI-CD_1ST
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: CI-CD_1ST
    spec:
      containers:
        - name: CI-CD_1ST
          image: ManikantaBandi/CI-CD_1ST:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: CI-CD_1ST-ssvc
spec:
  selector:
    app: CI-CD_1ST
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.
